### ISSUE TITLE
Aufgabe 00 Anderes HTML Element Fehlt

### ISSUE THREAD

**Issue by Logophoman** [2ndHendrix/GIS-SoSe-2020#1]
In deinem HTML ist nur ein Überschrift - Element drin! Ein weiteres HTML Element fehlt (nicht 2x h1 sondern 1x h1 und z.B. 1x p oder img...). Dieses Mal gibt es dafür auch noch keine Ampel, aber nächstes Mal solltest du die Aufgabe genauer lesen ;)

**Comment by 2ndHendrix** [comment]
Danke für die Kulanz, ich werde es gleich korrigieren und dann neu
hochladen. Ich hatte allerdings im htm file auch einen Paragraphen gesetzt.
Ich werde mich nochmal gründlich damit auseinandersetzen.
Mit freundlichen Grüßen
Manuel

Logophoman <notifications@github.com> schrieb am Mo., 27. Apr. 2020, 00:35:

**Comment by Logophoman** [comment]
Hey Manuel,

ich hatte mir tatsächlich dein HTML nicht so genau angeschaut, sondern nur gesehen, dass du ausschließlich fetten Text hast und ein H1 Tag benutzt. Der Fehler liegt ganz einfach daran, dass du dein h1 element mit einem / schließen musst, dann passt das Ganze wieder ;)

**Comment by Logophoman** [comment]
Wenn der Fehler behoben ist und die Seite geht, kannst du diesen Issue mit close schließen 😉

**Comment by 2ndHendrix** [comment]
Danke für den Hinweis, ich hatte mich auch schon gewundert.ivh lade das
aktuelle gleich hoch. Einen schönen Abend wünsche ich.

Logophoman <notifications@github.com> schrieb am Mo., 27. Apr. 2020, 17:40:

**Comment by Logophoman** [comment]
Top 👌🏻😊 danke dir auch 😉
